#174797463 add signup page
atlp-rwanda/script-heroes-frontend pull request #12
Opened 2020-11-15 14:52 UTC by Habinezajanvier

#### What does this PR do?
Adding the signup page to the web
#### Description of Task to be completed?
- Creating a Signup form
- Validating users input before submitting
- Routing signup from the landing page
#### How should this be manually tested?
- Clone the repo `git clone https://github.com/atlp-rwanda/script-heroes-frontend.git`
- Switch your working directory `cd script-heroes-frontend`
- checkout the branch `git checkout ft-user-signup-#174797463`
- Install all dependencies `yarn install`
- Start the server `yarn run dev`
#### What are the relevant pivotal tracker stories?
[#174797463](https://www.pivotaltracker.com/story/show/174797463)
#### Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/44426710/99188073-c3315300-2762-11eb-9f31-9955e5883733.png)

2020-11-25 12:52 UTC, dushimeemma approved these changes
Good job but check on the landing page

2020-11-30 07:43 UTC, jpirumvaa approved these changes
Apart from Coverage and the sign in button instead of signup, everything else is good to go on my end.

2020-11-30 07:43 UTC, jpirumvaa commented on src/components/SignupForm/index.js
> +          <Button style={{ width: "100%" }}>Sign in</Button>
The button should be signup instead of sign in

2020-11-30 09:10 UTC, Habinezajanvier commented on src/components/SignupForm/index.js
> +          <Button style={{ width: "100%" }}>Sign in</Button>
Done, Thank you brother

2020-11-30 12:37 UTC, valens10 approved these changes

2020-12-02 05:08 UTC, b0nbon1 requested changes

2020-12-02 05:08 UTC, b0nbon1 commented on debug.log
> +[1119/060149.572:ERROR:directory_reader_win.cc(43)] FindFirstFile: The system cannot find the path specified. (0x3)
could you add this `.gitignore`?

2020-12-02 05:08 UTC, b0nbon1 commented on src/App.scss
> +    font-size: 26pt;
on font-size I would suggest try using `rem`. research on the difference between rem, em and px

2020-12-02 05:08 UTC, b0nbon1 commented on src/components/HomePage.js
>  class NewHomePage extends Component {
be a bit consistent and choose between class components and functional components.

2020-12-02 05:08 UTC, b0nbon1 commented on src/tests/components/Alert.test.js
> +    expect(wrapper).toMatchSnapshot();
please avoiding using toMatchSnapshot, [read this for reference ](https://medium.com/@tomgold_48918/why-i-stopped-using-snapshot-testing-with-jest-3279fe41ffb2)

2020-12-02 05:08 UTC, b0nbon1 commented on src/tests/components/Signup.test.js
> +    expect(wrapper).toMatchSnapshot();
please avoiding using toMatchSnapshot, [read this for reference ](https://medium.com/@tomgold_48918/why-i-stopped-using-snapshot-testing-with-jest-3279fe41ffb2)

2020-12-02 05:08 UTC, b0nbon1 commented on src/tests/components/SignupImage.test.js
> +    expect(wrapper).toMatchSnapshot();
please avoiding using toMatchSnapshot, [read this for reference ](https://medium.com/@tomgold_48918/why-i-stopped-using-snapshot-testing-with-jest-3279fe41ffb2)

2020-12-02 05:08 UTC, b0nbon1 commented on webpack.config.js
> +      template: "./src/index.html",
there are no eslint rules, for quotation marks?

2020-12-07 14:14 UTC, b0nbon1 approved these changes

2020-12-07 16:40 UTC, merged