#174797464 Reset Password
atlp-rwanda/script-heroes-frontend pull request #14
Opened 2020-11-19 12:46 UTC by Junior-Adadie

#### What does this PR do?

This PR implements the whole process for resetting the password. 

#### Description of Task to be completed?

- create forgot password UI.
- Create reset password UI.
- Validate both UI
- Create an action for forgot password.
- Create a reducer for forgot password.
- Create a reducer for reset password.

#### How should this be manually tested?

- Clone this repo `https://github.com/atlp-rwanda/script-heroes-frontend.git`.
- Check out this branch `ch-setup-redux-#174797455`.
- Run `yarn`.
- Run `yarn start`.
- Register your email.
- Open this endpoint `/forgot`.
- Enter your email in the input box.
- Submit form
- Check if there is an email with reset password sent to you
- Click the reset button, it should redirect you to the reset password form.
- Fill in the form and submit.
- Try to login with the new password.
#### What are the relevant pivotal tracker stories?

[#174797464](https://www.pivotaltracker.com/story/show/174797464)
#### Screenshots (if appropriate)
<img width="1416" alt="Screen Shot 2020-11-19 at 14 46 27" src="https://user-images.githubusercontent.com/68109866/99668170-0ac32200-2a76-11eb-8647-651122d0724f.png">

2020-12-15 13:43 UTC, elvisiraguha reviewed
_.env_ file should not be pushed on the remote repo.

2020-12-16 07:14 UTC, dushimeemma approved these changes
Good job bro, but you have to work on css so that you can leave some space between main area and the footer and also on the form to enter new password you can work on it so that when the eye to view password is clicked can be checked else display as it is. also remove .env from remote.

2020-12-16 09:52 UTC, Junior-Adadie commented
> Good job bro, but you have to work on css so that you can leave some space between main area and the footer and also on the form to enter new password you can work on it so that when the eye to view password is clicked can be checked else display as it is. also remove .env from remote.

Thank you @dushimeemma , though what do you mean by leaving space between main area!!?

2020-12-17 13:23 UTC, Habinezajanvier requested changes

2020-12-17 13:23 UTC, Habinezajanvier commented on redux/actions/forgotPassword.js
> +const posting = axios.create({baseURL: `${process.env.REACT_APP_BACKEND_URL}`});
As all need this functionality, can't we make it global to prevent repeating ourselves

2020-12-17 16:48 UTC, elvisiraguha approved these changes

2020-12-18 09:55 UTC, Habinezajanvier approved these changes

2020-12-20 05:12 UTC, valens10 approved these changes

2020-12-21 01:29 UTC, merged