#174797458 Set up react router
atlp-rwanda/script-heroes-frontend pull request #5
Opened 2020-11-11 13:54 UTC by BeyFaith

#### What does this PR do?
Install and configure react router.
#### Description of Task to be completed?
- Install react router dome
- Configure the router
#### How should this be manually tested?
- Clone this repo git clone https://github.com/atlp-rwanda/script-heroes-frontend.git
- Switch your working directory cd script-heroes-frontend
- Checkout the branch `ch-set-up-react-router-#174797458`
Install all dependencies `yarn install`
Start the project `yarn start`
#### Any background context you want to provide?
- Yarn is a package manager like npm `
- If yarn is not working install it manually
- You can alternatively use npm insteas of yarn
#### What are the relevant pivotal tracker stories?
[#174797458](https://www.pivotaltracker.com/story/show/174797458)

2020-11-13 08:16 UTC, dushimeemma requested changes
Don't push node_modules

2020-11-13 13:56 UTC, dushimeemma approved these changes

2020-11-14 22:40 UTC, valens10 approved these changes

2020-11-15 05:34 UTC, Habinezajanvier approved these changes

2020-11-16 08:23 UTC, elvisiraguha approved these changes
LGTM

2020-11-16 09:04 UTC, ericus123 approved these changes

2020-11-16 10:34 UTC, b0nbon1 approved these changes

2020-11-16 10:34 UTC, merged