#174797455 Setup-Redux
atlp-rwanda/script-heroes-frontend pull request #8
Opened 2020-11-12 10:59 UTC by Junior-Adadie

#### What does this PR do?
This PR sets up redux in the project.
#### Description of Task to be completed?
- install redux.
- install react-redux.
- add redux devtool extension.
- create a store.
- setup reducers folder.
#### How should this be manually tested?
- Clone this repo `https://github.com/atlp-rwanda/script-heroes-frontend.git`.
- Check out this branch `ch-setup-redux-#174797455`.
- Install the redux dev tool in your browser, follow this link to download it if [you use chrome](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd).
- Run `yarn`.
- Run `yarn start`.
- Inspect the home with redux, the tree should be empty because we don't have any states yet.
#### What are the relevant pivotal tracker stories?
[#174797455](https://www.pivotaltracker.com/story/show/174797455)
#### Screenshots (if appropriate)
<img width="1438" alt="Screen Shot 2020-11-12 at 12 46 56" src="https://user-images.githubusercontent.com/68109866/98931431-ae488b80-24e6-11eb-9445-d5c69445673a.png">

2020-11-12 11:51 UTC, dushimeemma requested changes

2020-11-12 11:51 UTC, dushimeemma commented on src/index.js
>  import React from "react";
please separate redux store with index.js file and also try to use `thunk` and `applymiddleware`

2020-11-12 14:19 UTC, dushimeemma approved these changes

2020-11-12 16:16 UTC, Habinezajanvier approved these changes

2020-11-16 08:08 UTC, valens10 approved these changes

2020-11-16 09:24 UTC, ericus123 approved these changes

2020-11-16 09:39 UTC, BeyFaith approved these changes

2020-11-17 04:05 UTC, b0nbon1 commented
COuld you kindly rebase and resolve the conflicts?

2020-11-17 06:21 UTC, dushimeemma commented on redux/store.js
> +  applyMiddleware(...middlewares),
please wrap applyMiddleware and redux devtools in compose

2020-11-17 19:34 UTC, elvisiraguha approved these changes

2020-11-18 02:46 UTC, merged